# Generated by Django 4.1.7 on 2023-02-21 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(default='NO VALUE', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='NO VALUE', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='NO VALUE', max_length=255),
        ),
    ]
